# Define the base image to use to build the new image
FROM postgres:14.15-alpine

# Define the enviroment variables to use in the image
ENV POSTGRES_USER=postgresql
ENV POSTGRES_PASSWORD=12345
ENV POSTGRES_DB=ecommerce

# Export the default port for the database
EXPOSE 5432